[pytest]   # pytest 启动时会自动读取该配置
# -s :让print直接输出到控制台  -v 显示每个测试用例的名字和结果  --clean 清空历史结果，防止就报个污染新结果
addopts = -s -v --alluredir=./reports/allure_results --clean-alluredir
# 测试目录 指定pytest 去哪里找测试用例，即只扫描testcases/目录下的测试用例
testpaths = testcases
# 测试文件命名规则
python_files = test_*.py
# 测试类的命名规则
python_classes = Test*
# 测试函数的命名规则
python_functions = test_*
# 测试用例标签 可以按类型筛选执行，提高测试用例的组织能力
markers =
    api: 单接口测试
    scenario: 业务流程测试
    smoke: 冒烟测试
    regression: 回归测试

pythonpath = .